/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package commit_pipeline;

public class App {
    public int sum(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        App app = new App();
        
        System.out.println(app.sum(3, 5));
    }
}

class AppTest {
    private App app = new App();

    public void testSum() {
        assertEquals(5, app.sum(2, 3));
    }
}
